---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smiley
  namespace: faces
spec:
  selector:
    matchLabels:
      service: smiley
  template:
    metadata:
      labels:
        service: smiley
    spec:
      containers:
        - env:
            - name: FACES_SERVICE
              value: smiley
            - name: SMILEY
              value: HeartEyes
            - name: DELAY_BUCKETS
              value: 0,5,10,15,20,50,200,500,1500
          image: ghcr.io/buoyantio/faces-workload:2.0.0-rc.0
          imagePullPolicy: Always
          name: smiley
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      restartPolicy: Always
